GH actions and docker fixes and refactor (#302)
* Introduce docker bake and simplify build and push job

Pin VSCode Server version in VNC image due to incompatilibities in newer versions (cpp tools and ros extensions specifically cannot be installed to vscode server during image build)

Previously, the build and push job constitued of two parametrized jobs that were taking from the same template to build base and dependent vnc image. The .yml files themselves were somewhat convoluted and contained custom logic that should be unnecessary.  Since buildx was already used in workflows, no reason not to use its really good features, like bake. Also, buildx has been installed by default since docker v23.0, and current is v27, so really, there is no reason not to use it, hence changes in the Makefile too (also left previous build goal as build_legacy goal for clarity).
The convoluted logic of evaluating tags and targets manually, then passing them around to build and push jobs has been completely moved to docker-bake.hcl, which is way more extendable, and also can be used for both local and remote use. This also removes 2 .yml files which were dependent on each other, and instead makes the CI part of the system clean and simple. In addition, the job that actually builds the images will run faster now, as it is not explicitly sequential as before (basically, think that vnc job is now in some form of hot start mode, as it is not separated, so it can prepare its dependencies that are not dependent on the upstream image)

* Refactor bake config file, much more readable, structured and extendible, modify Makefile, add initial Dockerfile.deploy

* Enable push on new GH action, add some more comments to docker-bake.hcl

diff --git a/docker/Makefile b/docker/Makefile
--- a/docker/Makefile
+++ b/docker/Makefile
@@ -1,9 +1,14 @@
+SHELL := $(shell which bash)
+.SHELLFLAGS := -eu -o pipefail -c
+
+
 MAKEFLAGS+=--silent
 UID:=$(shell id -u)
 DOCKER_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
 PROJECT_DIR:=$(shell dirname ${DOCKER_DIR})
 NVIDIA_GPU:=$(shell (docker info | grep Runtimes | grep nvidia 1> /dev/null && command -v nvidia-smi 1>/dev/null 2>/dev/null && nvidia-smi | grep Processes 1>/dev/null 2>/dev/null) && echo '--runtime nvidia --gpus all' || echo '')
-FLAVOR=devel
+BUILDX_INSTALLED := $(shell docker buildx  1>/dev/null 2>&1 && echo true)
+FLAVOR=base
 IMAGE=ghcr.io/memristor/mep3
 
 .PHONY: all
@@ -21,14 +26,43 @@ vnc:
 	$(eval IMAGE=ghcr.io/memristor/mep3-vnc)
 	true
 
-build:
-	echo ${NO_CACHE_ARG}
-	DOCKER_BUILDKIT=1 docker build ${DOCKER_DIR} -f ${DOCKER_DIR}/Dockerfile.base -t mep3 ${DOCKER_ARGS} --build-arg UID=${UID}
-	[ ${FLAVOR} != 'devel' ] && \
-		DOCKER_BUILDKIT=1 docker build ${DOCKER_DIR} -f ${DOCKER_DIR}/Dockerfile.${FLAVOR} -t ${IMAGE} ${DOCKER_ARGS} || \
-		true
+deploy:
+	$(eval FLAVOR=deploy)
+	$(eval IMAGE=ghcr.io/memristor/mep3-deploy)
+	true
 
-run: test-nvidia
+multiple:
+	$(eval FLAVOR=multiple)
+	true
+
+## Test if the provided command exists
+exists/cmd/%:
+	@hash $(*) > /dev/null 2>&1 || (echo "ERROR: '$(*)' must be installed"; exit 1)
+
+## Test if the provided environment variable exists
+exists/env/%:
+	@if [ -z '$($(*))' ]; then echo "ERROR: environment variable '$*' not set" && exit 1; fi
+
+
+# Docker since version 23.0 has been including buildx by default, current live version is 27.2.1 as of 2024-09-16
+build: | exists/cmd/docker colors
+	if [ -n "${BUILDX_INSTALLED}" ]; then \
+		[ ${FLAVOR} == 'multiple' ] && docker buildx bake && exit 0; \
+		[ ${FLAVOR} == 'base' ] && docker buildx bake mep3 && exit 0; \
+		docker buildx bake mep3-${FLAVOR} && exit 0; \
+	else \
+		printf '%b\n' "${RED}Docker buildx is not present, it is highly recommended to install newer version of docker\n${NC}" || \
+		[ ${FLAVOR} = 'multiple' ] && \
+			DOCKER_BUILDKIT=1 docker build ${DOCKER_DIR} -f ${DOCKER_DIR}/Dockerfile.base -t mep3 ${DOCKER_ARGS} --build-arg UID=${UID} && \
+			DOCKER_BUILDKIT=1 docker build ${DOCKER_DIR} -f ${DOCKER_DIR}/Dockerfile.vnc -t mep3-vnc ${DOCKER_ARGS} && \
+			DOCKER_BUILDKIT=1 docker build ${DOCKER_DIR} -f ${DOCKER_DIR}/Dockerfile.deploy -t mep3-deploy ${DOCKER_ARGS} && exit 0; \
+		[ ${FLAVOR} = 'base' ] && \
+			DOCKER_BUILDKIT=1 docker build ${DOCKER_DIR} -f ${DOCKER_DIR}/Dockerfile.${FLAVOR} -t mep3 ${DOCKER_ARGS} --build-arg UID=${UID} && exit 0; \
+		[ ${FLAVOR} != 'base' ] && \
+			DOCKER_BUILDKIT=1 docker build ${DOCKER_DIR} -f ${DOCKER_DIR}/Dockerfile.${FLAVOR} -t mep3-${FLAVOR} ${DOCKER_ARGS} && exit 0; \
+	fi
+
+run: | exists/cmd/docker test-nvidia
 	docker run \
 		--net=host \
 		--ipc=host \
@@ -45,7 +79,7 @@ run: test-nvidia
 		-v ${PROJECT_DIR}:/memristor/ros2_ws/src/mep3:rw \
 		-d -it ${IMAGE} 1>/dev/null
 
-test-nvidia: colors
+test-nvidia: | exists/cmd/docker
 	lspci | grep -qi nvidia && base64 --decode massage | unxz || true
 	docker run --rm \
 		-e NVIDIA_DRIVER_CAPABILITIES=all ${NVIDIA_GPU} \
@@ -54,26 +88,26 @@ test-nvidia: colors
 	printf '%b\n' "${RED}Detected NVIDIA GPU in system, but missing packets, look up NVIDIA GPU section in README!\n${NC}" || \
 	true
 
-start-code-server:
+start-code-server: | exists/cmd/docker
 	docker exec -d -it mep3-${FLAVOR} bash -c 'pgrep code-server || code-server /memristor/ros2_ws/src/mep3' && \
 	xdg-open 'localhost:31415?folder=/memristor/ros2_ws/src/mep3'
 
-stop-code-server:
+stop-code-server: | exists/cmd/docker
 	docker exec -it mep3-${FLAVOR} pkill -f code-server
 
-exec:
+exec: | exists/cmd/docker
 	docker exec -it mep3-${FLAVOR} bash
 
-destroy:
+destroy: | exists/cmd/docker
 	docker container kill mep3-${FLAVOR} 1>/dev/null || true
 	docker container rm -f mep3-${FLAVOR} 1>/dev/null || true
 
-setup-default: colors
+setup-default: | exists/cmd/docker colors
 	docker exec -it mep3-${FLAVOR} sh -c '/usr/bin/setup.sh --default'
 	printf '%b\n%b\n' "${GREEN}Default setup complete!${NC}" \
 		"Run ${BOLD}make exec${NC} or ${BOLD}docker exec -it mep3-${FLAVOR}${NC} to access the container"
 
-setup-interactive: colors
+setup-interactive: | exists/cmd/docker colors
 	docker exec -it mep3-${FLAVOR} sh -c '/usr/bin/setup.sh --interactive'
 	printf '%b\n%b\n' "${GREEN}Interactive setup complete!${NC}" \
 		"Run ${BOLD}make exec${NC} or ${BOLD}docker exec -it mep3-${FLAVOR}${NC} to access the container"
