PoC with compose file

diff --git a/docker/Makefile b/docker/Makefile
--- a/docker/Makefile
+++ b/docker/Makefile
@@ -3,17 +3,12 @@ SHELL := $(shell which bash)
 
 
 MAKEFLAGS+=--silent
-UID:=$(shell id -u)
-DOCKER_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
-PROJECT_DIR:=$(shell dirname ${DOCKER_DIR})
-NVIDIA_GPU:=$(shell (docker info | grep Runtimes | grep nvidia 1> /dev/null && command -v nvidia-smi 1>/dev/null 2>/dev/null && nvidia-smi | grep Processes 1>/dev/null 2>/dev/null) && echo '--runtime nvidia --gpus all' || echo '')
-BUILDX_INSTALLED := $(shell docker buildx  1>/dev/null 2>&1 && echo true)
-FLAVOR=base
-IMAGE=ghcr.io/memristor/mep3
-
-.PHONY: all
-
-all: destroy run
+export UID:=$(shell id -u)
+export DOCKER_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
+export PROJECT_DIR:=$(shell dirname ${DOCKER_DIR})
+export NVIDIA_GPU:=$(shell (docker info | grep Runtimes | grep nvidia 1> /dev/null && command -v nvidia-smi 1>/dev/null 2>/dev/null && nvidia-smi | grep Processes 1>/dev/null 2>/dev/null) && echo 'true' || echo '')
+export FLAVOR=base
+export IMAGE=ghcr.io/memristor/mep3
 
 colors:
 	$(eval NC=\033[1;0m)
@@ -23,12 +18,7 @@ colors:
 
 vnc:
 	$(eval FLAVOR=vnc)
-	$(eval IMAGE=ghcr.io/memristor/mep3-vnc)
-	true
-
-deploy:
-	$(eval FLAVOR=deploy)
-	$(eval IMAGE=ghcr.io/memristor/mep3-deploy)
+	$(eval IMAGE=${IMAGE}-vnc)
 	true
 
 multiple:
@@ -36,33 +26,12 @@ multiple:
 	true
 
 exists/cmd/%:
-	@hash $(*) > /dev/null 2>&1 || (echo "ERROR: '$(*)' must be installed"; exit 1)
+	hash $(*) > /dev/null 2>&1 || (echo "ERROR: '$(*)' must be installed"; exit 1)
 
-exists/env/%:
-	@if [ -z '$($(*))' ]; then echo "ERROR: environment variable '$*' not set" && exit 1; fi
-
-
-build: | exists/cmd/docker colors
+build: | exists/cmd/docker
 	[ ${FLAVOR} == 'multiple' ] && docker buildx bake && exit 0; \
 	[ ${FLAVOR} == 'base' ] && docker buildx bake mep3 && exit 0; \
-	docker buildx bake mep3-${FLAVOR} && exit 0;
-
-run: | exists/cmd/docker test-nvidia
-	docker run \
-		--net=host \
-		--ipc=host \
-		--cap-add SYS_ADMIN \
-		--name mep3-${FLAVOR} \
-		--privileged \
-		--restart unless-stopped \
-		-e NVIDIA_DRIVER_CAPABILITIES=all ${NVIDIA_GPU} \
-		-e DISPLAY=${DISPLAY} \
-		-v ~/.Xauthority:/memristor/.host/.Xauthority:ro \
-		-v /tmp/.X11-unix/:/tmp/.X11-unix:rw \
-		-v /dev/dri:/dev/dri:ro \
-		-v /dev:/dev:rw \
-		-v ${PROJECT_DIR}:/memristor/ros2_ws/src/mep3:rw \
-		-d -it ${IMAGE} 1>/dev/null
+	docker buildx bake mep3-${FLAVOR} && exit 0; \
 
 test-nvidia: | exists/cmd/docker
 	lspci | grep -qi nvidia && base64 --decode massage | unxz || true
@@ -73,12 +42,19 @@ test-nvidia: | exists/cmd/docker
 	printf '%b\n' "${RED}Detected NVIDIA GPU in system, but missing packets, look up NVIDIA GPU section in README!\n${NC}" || \
 	true
 
-exec: | exists/cmd/docker
-	docker exec -it mep3-${FLAVOR} bash
+run: | exists/cmd/docker test-nvidia
+	if [ -n "${NVIDIA_GPU}" ]; then \
+		docker compose up -d mep3-${FLAVOR}-nvidia; \
+	else \
+		docker compose up -d mep3-${FLAVOR}; \
+	fi
 
 destroy: | exists/cmd/docker
-	docker container kill mep3-${FLAVOR} 1>/dev/null || true
-	docker container rm -f mep3-${FLAVOR} 1>/dev/null || true
+	docker compose kill --remove-orphans || true
+	docker compose down --remove-orphans
+
+exec: | exists/cmd/docker
+	docker exec -it mep3-${FLAVOR} bash
 
 setup-interactive: | exists/cmd/docker colors
 	docker exec -it mep3-${FLAVOR} sh -c '/usr/bin/setup.sh --interactive'
